apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: examspring
  name: examspring
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: examspring
status:
  loadBalancer: {}
